version: '3.7'
volumes:
  acme:

services:
  traefik:
    image: traefik:v2.4
    ports:
      - "80:80"
      - "443:443"
      - "8100:8000"
    expose:
      # traefik dashboard port
      - 8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # On map la conf statique dans le conteneur
      - ./config/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      # On map la conf dynamique statique dans le conteneur
      - ./config/traefik/config.yml:/etc/traefik/config.yml:ro
      # On map les certificats dans le conteneur
      - ./certs:/etc/certs:ro
#    secrets:
#      - auth_users
    networks:
      - proxy_network
    labels:
      # Permettre à ce conteneur d'être accessible par traefik
      # Pour plus d'information, voir : https://docs.traefik.io/providers/docker/#exposedbydefault
      - "traefik.enable=true"
      # Configures access to the traefik dashboard (auth required)
      - "traefik.http.routers.traefik_https.rule=Host(`admin.localhost`) && PathPrefix(`/dashboard`))"
      - "traefik.http.routers.traefik_https.entrypoints=websecure"
      - "traefik.http.routers.traefik_https.tls=true"
      - "traefik.http.routers.traefik_https.service=api@internal"
      - "traefik.http.routers.traefik_https.middlewares=traefik-auth"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=jpommier:$$apr1$$PoBGFKwl$$du5jU/.txpAh7wNIxGHTT."

networks:
  proxy_network:
    external: true